# Generated by Django 3.0.6 on 2020-05-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Certificado')),
                ('image', models.ImageField(upload_to='certificado', verbose_name='imagem')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='FormInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100, verbose_name='Nome do Evento')),
                ('date', models.DateField(verbose_name='Data do Evento')),
                ('body', models.TextField(verbose_name='Corpo')),
                ('date_creaded', models.DateField(auto_now=True)),
                ('planilha', models.FileField(upload_to='planilhas', verbose_name='Planilha')),
            ],
            options={
                'db_table': 'Eventos',
            },
        ),
    ]
